### ISSUE TITLE
NoSQL Challenge error

### ISSUE THREAD

**Issue by kmacedovarela** [architects4j/helidon-microstream-training-labs-foundation#5]
issue reported by @t0r0X 

while trying to solve "helidon-microstream-training-labs-foundation/acme-store-rest-nosql" I hit rock bottom at the end of the task, and had to peek at the solution "helidon-microstream-training-labs-foundation/solutions/acme-store-rest-nosql-solution".

My code was about equivalent, and the solution fails with same error during start-up. Details added below.

mvn clean package && java -jar target/acme-store-rest-nosql-solution.jar

[...]
2022.07.07 01:06:11 INFORMATION
one.microstream.integrations.cdi.types.extension.StorageExtension
!thread!: Processing StorageExtension:  1 found
2022.07.07 01:06:11 INFO org.jboss.weld.Bootstrap !thread!:
WELD-ENV-002001: Weld SE container 6f5b81c7-90e2-4ce1-bd2e-3fa85cb5cf95
shut down
Exception in thread "main"
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied
dependencies for type ProductRepository with qualifiers @Default
   at injection point [BackedAnnotatedField] @Inject private
org.a4j.product.ProductResource.repository
   at org.a4j.product.ProductResource.repository(ProductResource.java:0)

     at
org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
     at
org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
     at
org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
     at
org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
     at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
     at
org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:64)
     at
org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:62)
     at
org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
     at
org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
     at
java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
     at
java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
     at
java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
     at
java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
     at
java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
     at
java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by otaviojava** [comment]
There is a bug found o Helidon, the workaround that we have is to put this plugin to copy all the dependencies
Please, check this sample here:
https://github.com/architects4j/helidon-microstream-training-demos/blob/main/nosql/pom.xml#L74#L86
